### ISSUE TITLE
Consume through socket.io

### ISSUE THREAD

**Issue by vishal-verma14** [Blancduman/mediasoup-client-flutter#16]
hi @Blancduman, 

Thank you for mediasoup_client_flutter implementation. I have implemented the same but with socket.io rather than protoo. 
I am able to produce video on the server but unable to consume stream. I am able to get consumer object and passed them through onConsumer(consumer)  to renderer RTCVideoView. Can you please explain what are you doing on accept({}) that plays that video in RTCVideoView? 

thank you

**Comment by Blancduman** [comment]
Hi, @vishal-verma14 

It's callback function which tells to server that we are ready to receive stream.
