### ISSUE TITLE
example not working

### ISSUE THREAD

**Issue by salahkamal** [Blancduman/mediasoup-client-flutter#18]
Hello, thank you for your effort and the package .. I tried to run your example but it's not  working  for me .

**Comment by salahkamal** [comment]
I tried to use your package to but there is  an issue with the transport and  producer callback it doesn’t  trigger  when produce

**Comment by ZackMitkin** [comment]
Have you ran the example?

**Comment by salahkamal** [comment]
Yes it's ran but it doesn't work when i try to join !!
That's what I get
![Screenshot_20210729-164809](https://user-images.githubusercontent.com/19710233/127513675-3454f3ff-f3b0-42df-a250-e22efb1a2e9e.jpg)

**Comment by Blancduman** [comment]
I think server down. Tried yesterday. Use local server

чт, 29 июл. 2021 г., 17:51 salahkamal ***@***.***>:

**Comment by salahkamal** [comment]
Hello, on produce i have a problem the event doesn’t trigger 


`socket.emitWithAck('createTransport', {'transType': 'tx'},
                    ack: (data) async {
                  log('createTransport ' + data.toString());
                  // log('createTransport error ' + err.toString());
                  var sendTransport = device.createSendTransportFromMap(
                      data['params'],
                      producerCallback: _producerCallBack);
                  sendTransport.on('connectionstatechange', (state) {
                    switch (state) {
                      case 'connecting':
                        log('connecting');
                        break;

                      case 'connected':
                        //localVideo.srcObject = stream
                        log('connected');
                        break;

                      case 'failed':
                        sendTransport.close();
                        break;

                      default:
                        log('default');
                        break;
                    }
                  });
                  sendTransport.on('connect', (data2) {
                    log('sendTransport connect');
                    DtlsParameters parameters = data2['dtlsParameters'];
                    log('dtlsParameters ' +
                        // data['params']['dtlsParameters'].toString()
                        parameters.toMap().toString());
                    socket.emitWithAck('connectTransport', {
                      'transType': 'tx', // tx or rx
                      'dtlsParameters': parameters.toMap(),
                    }, ack: (data) {
                      log('connectTransport ' + data.toString());
                    });
                  });
                  var stream = await navigator.mediaDevices
                      .getUserMedia({'video': true});
                  var videoTrack = stream.getVideoTracks()[0];
                  RtpCodecCapability codec = device.rtpCapabilities.codecs
                      .firstWhere(
                          (RtpCodecCapability c) =>
                              c.mimeType.toLowerCase() == 'video/vp9',
                          orElse: () =>
                              throw 'desired vp9 codec+configuration is not supported');

                  try {
                    sendTransport.on('produce', () {
                      log('-----------produce-----------');
                    });
                    sendTransport.produce(
                      track: videoTrack,
                      codecOptions: ProducerCodecOptions(
                        videoGoogleStartBitrate: 1000,
                      ),
                      encodings: [
                        RtpEncodingParameters(scalabilityMode: 'S3T3_KEY'),
                      ],
                      stream: stream,
                      codec: codec,
                    );
                  } catch (e) {
                    await stream.dispose();
                  } finally {
                    await stream.dispose();
                    // sendTransport.close();
                  }
                });`

**Comment by Blancduman** [comment]
What event? Create transport?

вс, 1 авг. 2021 г., 17:40 salahkamal ***@***.***>:

**Comment by salahkamal** [comment]
No, that event => Transport.on('produce', (data){});

**Comment by salahkamal** [comment]
also as its described `Transport.produce()` used to create a Producer by using producer callback to receive a new Producer.
but when I produce the callback doesn’t execute and I don’t know why ??!

**Comment by Blancduman** [comment]
@salahkamal 
Maybe:
1) `socket.emitWithAck('connectTransport', ...` - you do not passing [transport Id](https://github.com/Blancduman/mediasoup-client-flutter/blob/main/example/lib/data/repositories/room_client_repository.dart#L299); and also you not using [`data2[callback]`](https://github.com/Blancduman/mediasoup-client-flutter/blob/main/example/lib/data/repositories/room_client_repository.dart#L301) after that emit;
2) Same with `sendTransport.on('produce', ...` - use [callback](https://github.com/Blancduman/mediasoup-client-flutter/blob/main/example/lib/data/repositories/room_client_repository.dart#L305);

Let me know did this solves your problem

**Comment by salahkamal** [comment]
Thank you 🙏 
It’s working now.

**Comment by Blancduman** [comment]
@salahkamal 👍

**Comment by salahkamal** [comment]
Hello again, Congratulations for the new releasing you made such a great work.
I have a question  can i disable WebRTC logs?

**Comment by Blancduman** [comment]
Hi. Thanks.

Right now - no.
Disable it for debug?

вт, 10 авг. 2021 г., 14:19 salahkamal ***@***.***>:
