### ISSUE TITLE
Question regarding publishing of package

### ISSUE THREAD

**Issue by ritvij14** [Blancduman/mediasoup-client-flutter#19]
Hello, will this package be published on pub.dev? Me and my colleagues are using this package for a project which I need to publish soon, so I wanted to know.

**Comment by Blancduman** [comment]
Ya. Let me finish migration to null safety. Wait till the end of weekend
for updates.

вт, 3 авг. 2021 г., 06:02 Ritvij Kumar Sharma ***@***.***>:

**Comment by ritvij14** [comment]
@Blancduman thanks for the update. One more thing, wanted to ask this because I saw you were a contributor in that project, do you have any idea as to when this will be made as the official updated protoo-client?
https://github.com/ZackMitkin/dart-protoo-client
Because it seems this is the most updated one when comparing with the current latest js protoo client.

**Comment by Blancduman** [comment]
Better to ask Zack

вт, 3 авг. 2021 г., 18:09 Ritvij Kumar Sharma ***@***.***>:

**Comment by ZackMitkin** [comment]
@ritvij14 I don't think you should use dart protoo-client for your personal projects. The reason I worked on fixing it from flutter-webrtc's implementation was just to get a demo/example going for mediasoup client. Protoo it's self is very minimal and has a lot less support than something like socket-io. You'll run into many issues using my protoo library patch and I'm not planning to update or maintain it.
If you want really want, you can just fork my branch and create a PR into flutter-webrtc's branch. They have published many packages to pub.dev and might be willing to maintain protoo client

**Comment by ritvij14** [comment]
@ZackMitkin alright, thanks! 👍🏻

**Comment by Blancduman** [comment]
[mediasoup_client_flutter](https://pub.dev/packages/mediasoup_client_flutter)
