### ISSUE TITLE
RTCVideoView orientation issue

### ISSUE THREAD

**Issue by salahkamal** [Blancduman/mediasoup-client-flutter#26]
RTCVideoView render video only on horizontal aspect and the looks like its rotated.

**Comment by salahkamal** [comment]
![Screenshot_1630496859](https://user-images.githubusercontent.com/19710233/131851165-8e29c389-1e62-41c2-824e-8ca466b9b7be.png)

**Comment by cloudwebrtc** [comment]
It seems strange, are you using a real device or an Android emulator?

@Blancduman Did you forget to add
`a=extmap:4 urn:3gpp:video-orientation\r\n`
When SDP is generated, this field will create a rotation information for rtp during screen transmission, so that the device will perform rotation correction during rendering after receiving the screen.

**Comment by Blancduman** [comment]
@salahkamal try this branch please: https://github.com/Blancduman/mediasoup-client-flutter/tree/refactor/entities

**Comment by salahkamal** [comment]
@cloudwebrtc @Blancduman I tried it on both real device and emulator android and ios and the problem seems not solved with the new branch, but i notice the problem happens for consumer's streams only and not for the local device stream as shown 
![Screenshot_1630639005](https://user-images.githubusercontent.com/19710233/131945910-9de63b47-7139-494a-8e5b-40ec563e7bbb.png)

**Comment by Blancduman** [comment]
@salahkamal update branch, I made changes, and try again please

**Comment by salahkamal** [comment]
@Blancduman Same problem, Can I help you with any logs?

**Comment by Blancduman** [comment]
@salahkamal update same branch; when you got your router rtp capabilities and right before loading device => remove `urn:3gpp:video-orientation` header extension.

```dart
rtpCapabilities.headerExtensions.removeWhere((he) => he.uri == 'urn:3gpp:video-orientation');
```

**Comment by Blancduman** [comment]
@salahkamal actually, you can use pub version

**Comment by salahkamal** [comment]
That’s solve my problem, thank you 🙏 😊
