### ISSUE TITLE
Remote video renderer not working when remote peer toggle webcam stream   

### ISSUE THREAD

**Issue by ChintanRajpara** [Blancduman/mediasoup-client-flutter#32]
When remote peer enables webcam for the first time it works but when remote peer turn OFF webcam and turn ON  webcam again this error is displayed inside RTCVideoRenderer ,  but when remote peer again toggles webcam it works fine. 

![image](https://user-images.githubusercontent.com/34347118/133550939-80e45640-4d09-4733-9bc2-bb785e485355.png)

![image](https://user-images.githubusercontent.com/34347118/133550681-4a4dc272-86c5-46c0-84cb-f836d74e36b6.png)

I am testing on our own mediasoup server, but this error was was there when I ran example code form thiss repository.  

testing on android device

**Comment by Blancduman** [comment]
Your device kind'na slow. You can wrap render.dispose() in peers/bloc in
future.delay

чт, 16 сент. 2021 г., 07:46 Chintan Rajpara ***@***.***>:

**Comment by ChintanRajpara** [comment]
My bad, old renderer was being rendered, I managed to solve that issue
