### ISSUE TITLE
flutter-webrtc / flutter-mediasoup-client 

### ISSUE THREAD

**Issue by NicolaiLassen** [Blancduman/mediasoup-client-flutter#4]
Hi Blancduman,

I also noticed that the flutter-mediasoup-client project was not going anywhere. So i started the porting of the web-client this week. After the initial development i found your repo; and i see you are father ahead than me. So I'm going to fork and continue the port from your repo . Could you detail the missing parts?

Thanks for this!
Best, 
Nicolai

**Comment by Blancduman** [comment]
Hi.

Actually, I'm currently working in an example branch and just don't
commit because there are some issues. At will finishing it at the end of
this week (prays).

**Comment by NicolaiLassen** [comment]
That sound great. Thanks again!

Best.
