### ISSUE TITLE
Can't Load Consumer Video VP9 with profile-id = 2

### ISSUE THREAD

**Issue by jack2992** [Blancduman/mediasoup-client-flutter#40]
Hi @Blancduman,
I have a issue can't load video with profile-id = 2
Can you help me to find the solution to solve it?
Example routerRtpCapabilities data:
![image](https://user-images.githubusercontent.com/77400417/146480050-272c1b93-80b8-45a1-a98f-0bbfdc52951c.png)

Thanks

**Comment by Blancduman** [comment]
It's happening on one device or all?

**Comment by Huynhtri027** [comment]
> Hi. It's happening on one device or all?

Hi @Blancduman

**Comment by jack2992** [comment]
> Hi. It's happening on one device or all?

Hi @Blancduman,
I have checked Android and IOS the same issue, If Web Client Join meeting and using VP9 (profile id = 2). Android and IOS Using VP8 work well, but can't see webcam web client.
Please help me to find the solution to solve it?
Thanks !

**Comment by Blancduman** [comment]
Try same scenario with my demo

пт, 17 дек. 2021 г., 13:15 jack2992 ***@***.***>:

**Comment by jack2992** [comment]
> 

Yes, @Blancduman 
I change url connect socket to my server 
Note: Server run with core mediasoup library and with config file routerRtpCapabilities support VP9 (profile-id =2)

**Comment by Blancduman** [comment]
Then something went wrong on the server side.

**Comment by Blancduman** [comment]
Let me know with results.
There was a guy from the land of baguettes. He still owe me a baguette...
Check your mediasoup config with official docs.

**Comment by Blancduman** [comment]
If this is still issue for you: share with me your environment. Via email

**Comment by jack2992** [comment]
Thanks Master
