### ISSUE TITLE
Where can i get the file 'package:my_project/my_signaling.dart' file?

### ISSUE THREAD

**Issue by abhineetagarwal** [Blancduman/mediasoup-client-flutter#42]
I am a beginner in dart programming language & I am struggling to understand what the code should look like.
Can someone help me to locate the `'package:my_project/my_signaling.dart'` file and also can someone let me know the definition of the below request method?
`final Map<String, dynamic> routerRtpCapabilities = await mySignaling.request('getRouterCapabilities');`

**Comment by abhineetagarwal** [comment]
Never mind. I got the solution....

**Comment by noelbank00** [comment]
@abhineetagarwal Can you tell what is the solution? I stuck into the same problem. 😞
