### ISSUE TITLE
Possible to include node server-side example?

### ISSUE THREAD

**Issue by ollydixon** [Blancduman/mediasoup-client-flutter#52]
Thanks for making this project.

Do you think it's possible to include a server-side example with the example project?

**Comment by ZackMitkin** [comment]
you can use https://github.com/Blancduman/mediasoup_client_flutter_example

with https://github.com/versatica/mediasoup-demo/tree/v3/server as the server.

**Comment by ollydixon** [comment]
@ZackMitkin thanks, when trying to build the client example I get ```Could not build the precompiled application for the device.```

**Comment by ollydixon** [comment]
```flutter pub upgrade``` fixed it.

**Comment by ollydixon** [comment]
@ZackMitkin seem to have it working but the room URL doesn't seem to work. Serevr is up and running and the url works for it 🫤

**Comment by ollydixon** [comment]
For anyone else, if you want to point towards a local server you need to include "roomId" param in the url.

```
RoomBloc(String? url)
      : super(
          // RoomState(
          //   url: url != null && url.isNotEmpty ? url.replaceAll('roomid', 'roomId') : 'https://v3demo.mediasoup.org/?roomId=aaaaa',
          // ),
          RoomState(url: "https://polydelic.asuscomm.com:55643/?roomId=local"),
        );
```

**Comment by ollydixon** [comment]
Is it even possible to overwrite the URL here? Seems to have no effect...

**Comment by ollydixon** [comment]
@ZackMitkin it would seem that locally it does not work. Same issue I'm having with my own code. Just a blank window on both sides.

**Comment by ollydixon** [comment]
Some more info

<img width="892" alt="Screenshot 2022-07-11 at 20 47 02" src="https://user-images.githubusercontent.com/6940726/178336232-bcc2dcff-806e-47c5-ad20-9c0e153d52dd.png">
<img width="1174" alt="Screenshot 2022-07-11 at 20 46 52" src="https://user-images.githubusercontent.com/6940726/178336239-6dcd87bc-c0c6-424d-9431-f71b6809a64c.png">
