### ISSUE TITLE
Dependency error: flutter_webrtc

### ISSUE THREAD

**Issue by un-hongly** [Blancduman/mediasoup-client-flutter#63]
<img width="810" alt="Screen Shot 2022-09-12 at 5 39 44 PM" src="https://user-images.githubusercontent.com/40728555/189634691-31906890-3382-46ea-8007-b2eb6ba0ea20.png">

I got this error during the app build. Seem after the bump flutter_webrtc.

**Comment by rawquesh** [comment]
@un-hongly  hey, are you able to build the app now?

**Comment by un-hongly** [comment]
@rawquesh I have discord but I'm not so familiar with it. This is my username Hongfy#1759.

**Comment by mohamedamr987** [comment]
try this one
https://github.com/flutter-webrtc/flutter-webrtc/issues/1079
