### ISSUE TITLE
Voice calls on iOS are too low

### ISSUE THREAD

**Issue by mymirror** [Blancduman/mediasoup-client-flutter#72]
When you open a voice call on iOS, the sound is almost inaudible, butit is fine on Android phones

**Comment by un-hongly** [comment]
> When you open a voice call on iOS, the sound is almost inaudible, butit is fine on Android phones

+1

**Comment by mymirror** [comment]
> > When you open a voice call on iOS, the sound is almost inaudible, butit is fine on Android phones
> 
> +1

0.8.5 solves this problem, you can also turn on the iPhone microphone to turn on the speaker mode yourself
